# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d48489f1103cacb0d8a81c152d41f41c6a0e78c447d7fa29441f82444d4d63a6ac0748f9f7fddd995e13d394674ec2e884f4a682523540d1d15ef73de039e52e

test:
  secret_key_base: df7d376aa20919a22082a660d754098358c4cb93c1193b7036b34f24fcc7d600f20d1d0797ae0299686de903351be45f9dc32ecf4a0c5485f0e05e9a1cea77cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
